import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2, MessageCircle, ShieldCheck, Wrench } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PageHero } from "@/components/site/PageHero";
import { Reveal, Stagger, StaggerItem } from "@/components/site/motion";
import { serviceCategories, services } from "@/content/services";
import { waLink } from "@/components/site/site-config";

export const metadata: Metadata = { title: "Servicios técnicos", description: "Reparación de celulares, computadoras, consolas y tecnología. Diagnóstico profesional, presupuesto previo y garantía informada en ServiTec." };
const accents = { cyan: "border-cyan-200 bg-cyan-50 text-cyan-800 group-hover:border-cyan-400", blue: "border-blue-200 bg-blue-50 text-blue-800 group-hover:border-blue-400", violet: "border-violet-200 bg-violet-50 text-violet-800 group-hover:border-violet-400", amber: "border-amber-200 bg-amber-50 text-amber-800 group-hover:border-amber-400" };

export default function ServiciosPage() {
  return <>
    <PageHero eyebrow="Servicios técnicos" title="Cuidamos la tecnología que usás todos los días" description="Diagnóstico, reparación y mantenimiento para celulares, computadoras, consolas y mucho más. Elegí tu equipo para conocer el servicio específico."><div className="flex flex-wrap justify-center gap-3"><Button asChild size="lg" className="bg-whatsapp text-whatsapp-foreground hover:bg-whatsapp/90"><a href={waLink("Hola ServiTec, quiero consultar por un servicio técnico")} target="_blank" rel="noopener noreferrer"><MessageCircle className="size-4" /> Consultar por WhatsApp</a></Button><Button asChild size="lg" variant="outline" className="border-white/20 bg-white/5 text-white hover:bg-white/10 hover:text-white"><Link href="#equipos">Ver servicios</Link></Button></div></PageHero>
    <main><section className="container-page grid gap-4 py-10 sm:grid-cols-3 sm:py-14"><div className="flex gap-3 rounded-2xl border bg-card p-5"><Wrench className="size-5 shrink-0 text-primary" /><div><p className="font-semibold">Diagnóstico profesional</p><p className="mt-1 text-sm text-muted-foreground">Revisamos antes de avanzar.</p></div></div><div className="flex gap-3 rounded-2xl border bg-card p-5"><CheckCircle2 className="size-5 shrink-0 text-primary" /><div><p className="font-semibold">Presupuesto previo</p><p className="mt-1 text-sm text-muted-foreground">Conocé la alternativa disponible.</p></div></div><div className="flex gap-3 rounded-2xl border bg-card p-5"><ShieldCheck className="size-5 shrink-0 text-primary" /><div><p className="font-semibold">Garantía informada</p><p className="mt-1 text-sm text-muted-foreground">Según cada trabajo realizado.</p></div></div></section>
      <section id="equipos" className="container-page scroll-mt-24 pb-16 lg:pb-24"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow text-primary">Elegí tu equipo</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight">¿Qué dispositivos reparamos?</h2><p className="mt-3 text-muted-foreground">Cada categoría tiene su propia página con reparaciones habituales, modelos, preguntas frecuentes y una consulta ya preparada para tu equipo.</p></div><div className="mt-10 space-y-12">{serviceCategories.map((category) => { const categoryServices = services.filter((service) => service.category === category); return <Reveal key={category}><div className="mb-5 flex items-center gap-3"><span className="h-px flex-1 bg-border" /><Badge className="bg-primary/10 px-3 py-1 text-primary hover:bg-primary/10">{category}</Badge><span className="h-px flex-1 bg-border" /></div><Stagger className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categoryServices.map((service) => { const Icon = service.icon; return <StaggerItem key={service.slug}><Link href={`/servicios/${service.slug}`} className="group flex h-full flex-col rounded-2xl border bg-card p-5 shadow-soft transition-all duration-300 hover:-translate-y-1 hover:border-primary/30 hover:shadow-soft-lg"><div className={`flex size-10 items-center justify-center rounded-xl border transition-colors ${accents[service.accent]}`}><Icon className="size-5" /></div><h3 className="mt-4 font-display text-lg font-bold">{service.shortTitle}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{service.description}</p><span className="mt-5 flex items-center gap-1 text-sm font-semibold text-primary">Ver servicio <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></Link></StaggerItem>; })}</Stagger></Reveal>; })}</div></section></main>
    <section className="border-t bg-muted/40 py-14"><div className="container-page flex flex-col items-center gap-4 text-center"><h2 className="font-display text-2xl font-bold">¿No ves tu dispositivo?</h2><p className="max-w-xl text-sm text-muted-foreground">Escribinos igual. Contanos marca, modelo y falla para evaluar cómo podemos ayudarte.</p><Button asChild size="lg"><a href={waLink("Hola ServiTec, necesito consultar por un equipo que no veo en Servicios")} target="_blank" rel="noopener noreferrer">Consultar mi equipo <ArrowRight className="size-4" /></a></Button></div></section>
  </>;
}
