import type { LucideIcon } from "lucide-react";
import { BatteryCharging, BookOpen, Camera, Gamepad2, Laptop, RadioTower, Smartphone, Tablet, Tv } from "lucide-react";

export type Service = {
  slug: string; title: string; shortTitle: string; category: "Apple" | "Smartphones" | "Tecnología";
  description: string; intro: string; icon: LucideIcon; accent: "cyan" | "blue" | "violet" | "amber";
  repairs: string[]; models: string[]; highlights: [string, string][]; faqs: [string, string][];
};

const common = [
  ["¿El diagnóstico tiene costo?", "Consultá el costo de diagnóstico antes del ingreso. Según las condiciones vigentes, puede aplicarse un cargo si no aceptás la reparación; te lo informamos para tu caso."],
  ["¿La reparación tiene garantía?", "Sí. Te informamos la garantía correspondiente al trabajo y al repuesto utilizado al momento de presupuestar."],
] as [string, string][];

const makeService = (service: Omit<Service, "faqs" | "highlights"> & { faqs?: [string, string][]; highlights?: [string, string][] }): Service => ({
  ...service,
  highlights: service.highlights ?? [["Diagnóstico claro", "Te explicamos la falla antes de avanzar."], ["Presupuesto previo", "Conocé la alternativa disponible."], ["Atención directa", "Coordiná tu consulta por WhatsApp."]],
  faqs: [...(service.faqs ?? []), ...common],
});

export const services: Service[] = [
  makeService({ slug: "iphone", title: "Servicio técnico para iPhone", shortTitle: "iPhone", category: "Apple", description: "Diagnóstico y reparación para iPhone con atención personalizada.", intro: "Pantalla, batería, cámaras, carga y fallas de placa. Revisamos tu iPhone y te damos un presupuesto claro antes de repararlo.", icon: Smartphone, accent: "cyan", repairs: ["Cambio de pantalla", "Reemplazo de batería", "Reparación de cámara", "Conector de carga", "Daño por líquido", "Botones y parlantes"], models: ["iPhone 17 Pro Max", "iPhone 17 Pro", "iPhone 16", "iPhone 15", "iPhone 14", "iPhone 13", "iPhone SE"], highlights: [["Atención ágil", "Coordinamos el ingreso de tu equipo."], ["Diagnóstico claro", "Te explicamos la falla antes de avanzar."], ["Garantía", "En los trabajos y repuestos correspondientes."]], faqs: [["¿Reparan iPhone con daño por agua?", "Sí, evaluamos el alcance de la humedad y las alternativas de reparación."], ["¿Pueden reparar Face ID o Touch ID?", "Consultanos con el modelo y la falla para confirmar la evaluación técnica."]] }),
  makeService({ slug: "ipad", title: "Servicio técnico para iPad", shortTitle: "iPad", category: "Apple", description: "Reparación de pantallas, baterías y carga para iPad.", intro: "Atendemos iPad, iPad Air, iPad mini y iPad Pro. Diagnosticamos fallas de pantalla, batería, carga y uso diario.", icon: Tablet, accent: "blue", repairs: ["Cambio de pantalla y táctil", "Cambio de batería", "Conector de carga", "Cámaras", "Botones", "Diagnóstico de placa"], models: ["iPad Pro", "iPad Air", "iPad mini", "iPad 10ª gen.", "iPad 9ª gen."], faqs: [["¿Reparan el vidrio del iPad?", "Evaluamos si el daño afecta sólo el vidrio o también el display/táctil."], ["¿Mi iPad no carga, tiene arreglo?", "Sí, revisamos conector, batería y circuito de carga según el caso."]] }),
  makeService({ slug: "macbook", title: "Servicio técnico para MacBook", shortTitle: "MacBook", category: "Apple", description: "Mantenimiento y reparación para notebooks Apple.", intro: "Revisamos MacBook Air, Pro e Intel/Apple Silicon para resolver problemas de pantalla, batería, teclado, carga y rendimiento.", icon: Laptop, accent: "violet", repairs: ["Cambio de pantalla", "Batería", "Teclado y trackpad", "Conector de carga", "Limpieza interna", "Diagnóstico de placa"], models: ["MacBook Air M1/M2/M3", "MacBook Pro 13", "MacBook Pro 14", "MacBook Pro 16", "MacBook Intel"], faqs: [["¿Reparan MacBook que no enciende?", "Sí, hacemos diagnóstico para identificar si la falla es de energía, pantalla o placa."], ["¿Pueden cambiar la batería?", "Evaluamos el modelo y el estado de la batería antes de cotizar."]] }),
  makeService({ slug: "samsung", title: "Servicio técnico para Samsung", shortTitle: "Samsung", category: "Smartphones", description: "Reparación para las líneas Galaxy S, Z, Note, A, M y J.", intro: "Pantalla, batería, cámara, tapa, carga y daños por humedad: revisamos tu Samsung para que vuelva a acompañarte todos los días.", icon: Smartphone, accent: "blue", repairs: ["Pantalla", "Batería", "Tapa trasera", "Cámara", "Conector de carga", "Daño por líquido"], models: ["Galaxy S", "Galaxy Z", "Galaxy Note", "Galaxy A", "Galaxy M", "Galaxy J"], faqs: [["¿Reparan pantallas AMOLED?", "Consultanos con el modelo para confirmar el repuesto y la alternativa de reparación."], ["¿Cambian tapas traseras?", "Sí, revisamos el modelo y el daño para cotizar."]] }),
  makeService({ slug: "motorola", title: "Servicio técnico para Motorola", shortTitle: "Motorola", category: "Smartphones", description: "Reparación de Motorola Edge, Razr, Moto G, Moto E y más.", intro: "Solucionamos fallas de pantalla, batería, audio, cámaras y carga para teléfonos Motorola actuales y clásicos.", icon: Smartphone, accent: "cyan", repairs: ["Pantalla", "Batería", "Audio y micrófono", "Cámara", "Carga", "Daño por agua"], models: ["Motorola Edge", "Motorola Razr", "Moto G", "Moto E", "Moto One", "Moto X"], faqs: [["¿Reparan el plegable Motorola Razr?", "Sí, consultanos con el modelo exacto y el tipo de daño."], ["¿Mi Moto G no carga?", "Podemos revisar conector, batería y placa de carga."]] }),
  makeService({ slug: "huawei", title: "Servicio técnico para Huawei", shortTitle: "Huawei", category: "Smartphones", description: "Servicio para Huawei Pura, Mate, P, Nova, Y, Honor y más.", intro: "Revisamos pantallas, baterías, cámaras y sistemas de carga en equipos Huawei y Honor.", icon: Smartphone, accent: "amber", repairs: ["Pantalla", "Batería", "Cámara", "Carga", "Botones", "Daño por líquido"], models: ["Huawei Pura", "Huawei Mate", "Huawei P", "Huawei Nova", "Huawei Y", "Honor"], faqs: [["¿Reparan Huawei sin servicios de Google?", "Podemos evaluar la reparación de hardware de tu equipo; consultanos por tu caso."], ["¿Cambian pantallas Huawei?", "Sí, según disponibilidad para el modelo específico."]] }),
  makeService({ slug: "xiaomi", title: "Servicio técnico para Xiaomi", shortTitle: "Xiaomi", category: "Smartphones", description: "Reparación para Xiaomi, Redmi, POCO, Black Shark y tablets.", intro: "Te ayudamos con problemas de pantalla, batería, carga, reinicios, cámaras y daño por líquido en tu equipo Xiaomi.", icon: Smartphone, accent: "amber", repairs: ["Pantalla", "Batería", "Carga", "Reinicios", "Cámara", "Daño por líquido"], models: ["Xiaomi", "Redmi", "POCO", "Black Shark", "Xiaomi Pad"], faqs: [["¿Reparan Xiaomi que se reinicia?", "Sí, hacemos una revisión para detectar si el problema es de software, batería o placa."], ["¿Pueden reparar un POCO?", "Sí, consultanos con el modelo y la falla."]] }),
  makeService({ slug: "sony", title: "Servicio técnico para Sony", shortTitle: "Sony", category: "Smartphones", description: "Servicio para Xperia actuales y líneas clásicas.", intro: "Reparamos pantalla, batería, cámaras, audio y carga en equipos Sony Xperia según diagnóstico y disponibilidad.", icon: Smartphone, accent: "violet", repairs: ["Pantalla", "Batería", "Cámara", "Audio", "Carga", "Daño por líquido"], models: ["Xperia 1", "Xperia 5", "Xperia 10", "Xperia Pro", "Líneas clásicas"], faqs: [["¿Reparan Xperia antiguos?", "Consultanos el modelo exacto para evaluar la factibilidad."], ["¿Pueden solucionar problemas de cámara?", "Sí, revisamos módulo, software y conexiones según el equipo."]] }),
  makeService({ slug: "notebooks", title: "Reparación de notebooks", shortTitle: "Notebooks", category: "Tecnología", description: "Service para HP, Lenovo, Dell, ASUS, Acer, MSI, Surface y más.", intro: "Reparamos notebooks para estudio, trabajo y gaming: pantallas, bisagras, teclados, cooler, energía, almacenamiento y rendimiento.", icon: Laptop, accent: "cyan", repairs: ["Pantalla", "Bisagras", "Teclado", "Cooler y pasta térmica", "SSD y RAM", "Conector de carga"], models: ["HP", "Lenovo", "Dell", "ASUS", "Acer", "MSI", "Microsoft Surface"], faqs: [["¿Reparan bisagras rotas?", "Sí, evaluamos la carcasa, bisagras y pantalla para definir la reparación."], ["¿Pueden mejorar una notebook lenta?", "Sí, revisamos SSD, memoria, temperatura y sistema para recomendar mejoras."]] }),
  makeService({ slug: "gopro", title: "Servicio técnico para GoPro", shortTitle: "GoPro", category: "Tecnología", description: "Reparación para GoPro HERO, MAX, Fusion, Session, Karma y accesorios.", intro: "Revisamos cámaras de acción GoPro con fallas de lente, pantalla, batería, carga, humedad o uso intenso.", icon: Camera, accent: "blue", repairs: ["Lente y carcasa", "Pantalla", "Batería", "Carga", "Daño por humedad", "Diagnóstico general"], models: ["GoPro HERO", "GoPro MAX", "GoPro Fusion", "GoPro Session", "GoPro Karma"], faqs: [["¿Reparan GoPro mojadas?", "Podemos evaluar el daño por humedad y las opciones de reparación."], ["¿Mi GoPro no enciende?", "Revisamos batería, alimentación y placa según el diagnóstico."]] }),
  makeService({ slug: "drones", title: "Servicio técnico para drones", shortTitle: "Drones", category: "Tecnología", description: "Reparación para DJI, Autel, Parrot, GoPro Karma y drones genéricos.", intro: "Evaluamos golpes, fallas de cámara, gimbal, motores, sensores y alimentación para que vuelvas a volar con seguridad.", icon: RadioTower, accent: "violet", repairs: ["Gimbal y cámara", "Motores", "Sensores", "Brazos y carcasa", "Batería", "Diagnóstico tras golpe"], models: ["DJI", "Autel", "Parrot", "GoPro Karma", "Drones genéricos"], faqs: [["¿Reparan drones que se cayeron?", "Sí, evaluamos brazos, motores, sensores y cámara antes de cotizar."], ["¿Pueden reparar el gimbal?", "Consultanos modelo y falla; revisamos la factibilidad técnica."]] }),
  makeService({ slug: "consolas", title: "Servicio técnico para consolas", shortTitle: "Consolas", category: "Tecnología", description: "Service para PlayStation, Xbox, Nintendo y Steam Deck.", intro: "Atendemos fallas de HDMI, lectura, temperatura, encendido, mandos y mantenimiento para tus consolas.", icon: Gamepad2, accent: "cyan", repairs: ["HDMI", "Drift y mandos", "Lectura", "Temperatura", "Encendido", "Limpieza interna"], models: ["PlayStation 4", "PlayStation 5", "Xbox One", "Xbox Series", "Nintendo Switch", "Steam Deck"], faqs: [["¿Reparan HDMI de PS5 y Xbox?", "Sí, revisamos el conector y el circuito de video según el caso."], ["¿Solucionan drift de joystick?", "Sí, diagnosticamos sticks, botones y conexión del mando."]] }),
  makeService({ slug: "ereaders", title: "Servicio técnico para eReaders", shortTitle: "eReader", category: "Tecnología", description: "Reparación para Kindle, Kobo, PocketBook, Sony Reader, Nook y más.", intro: "Revisamos pantallas de tinta electrónica, batería, carga, táctil, luz y fallas de encendido en lectores digitales.", icon: BookOpen, accent: "amber", repairs: ["Pantalla e-ink", "Batería", "Carga", "Táctil", "Luz frontal", "Encendido"], models: ["Kindle", "Kobo", "PocketBook", "Sony Reader", "Nook"], faqs: [["¿Reparan pantalla de Kindle rota?", "Consultanos el modelo y el tipo de daño para evaluar la alternativa."], ["¿Mi eReader no carga?", "Revisamos batería, conector y circuito de carga."]] }),
  makeService({ slug: "smart-tv", title: "Servicio técnico para Smart TV", shortTitle: "Smart TV", category: "Tecnología", description: "Reparación para Samsung, LG, Sony, Philips, TCL, Hisense y más.", intro: "Diagnosticamos Smart TV con problemas de imagen, HDMI, audio, encendido y funcionamiento general.", icon: Tv, accent: "blue", repairs: ["Imagen y retroiluminación", "HDMI", "Audio", "Encendido", "Fuente", "Diagnóstico general"], models: ["Samsung", "LG", "Sony", "Philips", "TCL", "Hisense"], faqs: [["¿Reparan TV sin imagen?", "Sí, evaluamos retroiluminación, panel y placas para definir la solución."], ["¿Mi Smart TV no prende?", "Revisamos fuente, placa principal y el tipo de falla."]] }),
];

export const serviceCategories = ["Apple", "Smartphones", "Tecnología"] as const;
export function getService(slug: string) { return services.find((service) => service.slug === slug); }
