import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const require=createRequire(`${process.env.TEMP}/servitec-qa-tools/package.json`);const {chromium}=require('playwright');const browser=await chromium.launch({channel:'chrome',headless:true});const results=[];
async function setup(options={}){const c=await browser.newContext(options);await c.route('**/api/**',r=>{assert.equal(r.request().method(),'GET');const p=new URL(r.request().url()).pathname;if(p==='/api/equipos'||p==='/api/productos')return r.fulfill({json:[]});if(p==='/api/componentes')return r.fulfill({json:{catalog:{}}});return r.continue();});return c;}
try{
 const c=await setup({viewport:{width:1440,height:900}});const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/hydrat/i.test(m.text()))errors.push(m.text());});
 await p.goto('http://127.0.0.1:3100/');await p.locator('[data-ready=true]').waitFor();await p.waitForFunction(()=>document.documentElement.classList.contains('lenis'));await p.waitForTimeout(900);
 await p.screenshot({path:'artifacts/qa/premium-home-desktop.png'});
 const button=p.getByRole('link',{name:'Reparar mi equipo',exact:true});const width=await button.evaluate(e=>e.getBoundingClientRect().width);await button.hover();await p.waitForTimeout(500);assert.ok(await button.locator('[class*="labels"]').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m42<0));assert.equal(await button.evaluate(e=>e.getBoundingClientRect().width),width);await button.focus();assert.equal(await button.evaluate(e=>document.activeElement===e),true);
 await p.mouse.move(20,300);await p.mouse.wheel(0,500);await p.waitForTimeout(100);assert.ok(await p.evaluate(()=>scrollY)>0);await p.waitForTimeout(900);assert.ok(Math.abs(await p.evaluate(()=>scrollY)-500)<10);results.push('Desktop Lenis wheel responds within 100ms and settles without overshoot');
 await p.getByRole('button',{name:/Abrir carrito/}).first().click();await p.waitForFunction(()=>document.documentElement.classList.contains('lenis-stopped'));const locked=await p.evaluate(()=>scrollY);await p.mouse.wheel(0,400);await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>scrollY),locked);await p.getByRole('button',{name:'Cerrar carrito'}).click();await p.waitForFunction(()=>!document.documentElement.classList.contains('lenis-stopped'));results.push('Cart modal stops background scroll and restores it');
 await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(300);await p.getByRole('link',{name:'Reparar mi equipo',exact:true}).click();await p.waitForURL(/servicios/);await p.waitForFunction(()=>document.documentElement.classList.contains('lenis'));await p.getByRole('link',{name:'Ver servicios',exact:true}).click();await p.waitForTimeout(1200);const top=await p.locator('#equipos').evaluate(e=>e.getBoundingClientRect().top);assert.ok(top>=0&&top<140,`anchor top ${top}`);results.push('Service CTA and #equipos anchor land below header');
 await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(200);const wa=p.getByRole('link',{name:'Consultar por WhatsApp',exact:true});assert.ok((await wa.getAttribute('href')).startsWith('https://wa.me/5491124873190?'));await wa.focus();assert.equal(await wa.evaluate(e=>document.activeElement===e),true);await p.keyboard.press('PageDown');await p.waitForTimeout(500);assert.ok(await p.evaluate(()=>scrollY)>0);results.push('WhatsApp destination intact, keyboard focus and PageDown functional');
 await p.goto('http://127.0.0.1:3100/');await p.locator('[data-ready=true]').waitFor();await p.waitForTimeout(900);
 const performance=await p.evaluate(()=>new Promise(resolve=>{let last=window.performance.now(),start=last,frames=[];const interval=setInterval(()=>scrollBy({top:25,behavior:'instant'}),50);function frame(t){frames.push(t-last);last=t;if(t-start<3000)requestAnimationFrame(frame);else{clearInterval(interval);frames=frames.slice(5).sort((a,b)=>a-b);resolve({mean:frames.reduce((a,b)=>a+b,0)/frames.length,p95:frames[Math.floor(frames.length*.95)],frames:frames.length});}}requestAnimationFrame(frame);}));await writeFile('artifacts/qa/premium-performance.json',JSON.stringify(performance));
 await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(350);assert.equal(await p.locator('[data-logo-scene]').count(),0);assert.equal(await p.evaluate(()=>document.documentElement.classList.contains('lenis')),false);assert.ok(await p.locator('h1').evaluate(e=>getComputedStyle(e).opacity==='1'));results.push('Live reduced motion disables Lenis/3D and preserves visible content');
 await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('[data-ready=true]').waitFor();assert.equal(await p.locator('[data-logo-scene]').count(),1);assert.deepEqual(errors,[]);await c.close();
 for(const width of [390,768]){const m=await setup({viewport:{width,height:900},isMobile:true,hasTouch:true});const page=await m.newPage();await page.goto('http://127.0.0.1:3100/');await page.locator('[data-ready=true]').waitFor();await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.documentElement.classList.contains('lenis')),false);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:`artifacts/qa/premium-home-${width}.png`});await page.getByRole('button',{name:'Abrir menú'}).click();await page.keyboard.press('Escape');await page.getByRole('link',{name:'Reparar mi equipo',exact:true}).click();await page.waitForURL(/servicios/);results.push(`${width}px touch: native scroll, GLB, no overflow, menu and CTA passed`);await m.close();}
 await writeFile('artifacts/qa/premium-results.json',JSON.stringify({results,performance},null,2));console.log(results.join('\n'));console.log(performance);
}finally{await browser.close();}
